### ISSUE TITLE
`load()` method in `Importer` class loads duplicate scanned classes.

### ISSUE THREAD

**Issue by Nhahan** [tiny-nestjs/auto-injectable#39]
### Discussion

```ts
  static load(patterns: string[]): AutoClasses {
    const importer = new Importer();
    const pathNames = importer.matchGlob(patterns);
    const foundClasses = pathNames.map((pathName) => importer.scan(pathName));
    return foundClasses.reduce(
      (merged, found) => ({
        providers: [...merged.providers, ...found.providers],
        controllers: [...merged.controllers, ...found.controllers],
        exports: [...merged.exports, ...found.providers],
      }),
      { providers: [], controllers: [], exports: [] },
    );
  }
```
If `@ComponentScan()` has an array parameter, it would have duplicate classses.
- ex) `@ComponentScan(['src', 'src/animal'])`

### Checklist

- [X] Are you add enough explanations for issue ?
- [X] Did you check if there are other issues with the same content as this issue ?

**Comment by Nhahan** [comment]
not really hard to solve.
I think
```ts
return foundClasses.reduce(
      (merged, found) => ({
        providers: [...merged.providers, ...found.providers],
        controllers: [...merged.controllers, ...found.controllers],
        exports: [...merged.exports, ...found.providers],
      }),
      { providers: [], controllers: [], exports: [] },
    );
```
Just change `[]` to `Set` will solve the bug.

**Comment by hubtwork** [comment]
It's nice idea to resolve that issue. But in philosophical thinking, i think it must be treated as error.
If parameters have `duplicated scanning-scope`, i think this is a human error.

What do you think @player31-kks  @Nhahan ?

**Comment by Nhahan** [comment]
@hubtwork
You mean that instead of handling this with `Set`, it should throw an error like https://github.com/tiny-nestjs/auto-injectable/pull/36?

**Comment by hubtwork** [comment]
I just give you a proposal 😄 
yeah... like #36  it's user(developer)'s mistake  i think ✌️

**Comment by Nhahan** [comment]
let me have a conversation with @player31-kks 😆
Thank you for your advise!!

**Comment by player31-kks** [comment]
I agree with both of you 
But I'd rather have the user use it without errors.😀

**Comment by Nhahan** [comment]
Maybe we can talk about this issue later. for now, I'll merge the PR of this issue.
