### ISSUE TITLE
`E2E Test`

### ISSUE THREAD

**Issue by player31-kks** [tiny-nestjs/auto-injectable#40]
### Discussion

We don't currently have an e2e test, and we want to create one.

### Checklist

- [X] Are you add enough explanations for issue ?
- [X] Did you check if there are other issues with the same content as this issue ?

**Comment by Nhahan** [comment]
Good.

**Comment by hubtwork** [comment]
👍

**Comment by Nhahan** [comment]
As ths issue is outdated, this will be discussed later
